### ISSUE TITLE
V2 Test Issues

### ISSUE THREAD

**Issue by jtuhtan** [mcrooks83/rapid_sensor_app#4]
V2 Issue 1) V2 data are placed into folders named Scenario_01/Run_01 where both .HIG and their matching .IMP files are located. The user then selects the Scenario_01 folder and then "Import Scenario". The green status bar alternates back and forth, but the data are not loaded or shown in the Console.

Error message:

loading scenario
sensor version: 2
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Spyder\pkgs\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Admin\OneDrive - TalTech\Projects\2023_EE_Sensor_Software\Software\2024.02.14_Beta\rapid_sensor_app-main\UI_Components\LoadScenario.py", line 171, in load_scenario
    process.start()
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 93, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
_pickle.PicklingError: Can't pickle <function load_scenario_from_directory at 0x000002338E423820>: it's not the same object as API.rapid_api.load_scenario_from_directory

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 126, in _main
EOFError: Ran out of input

**Comment by jtuhtan** [comment]
V2 Issue 2) After the user loads the HIG and IMP files, the accelerometer scaling of the HIG data is incorrect. The HIG values should have a mean value of nearly 10 m/s-2, which is approximately gravity, and overlay with the red IMU acceleration data. After converting the binary HIG accelerometer values to floats, they can be divided by a gain factor of 10 to convert to units of "g".

Tried to change "self.parameters['hig_gain'] = 10" in Params.py but it did not change the result?

**Comment by mcrooks83** [comment]
put division back in but still isnt correct, currently not sure why

**Comment by mcrooks83** [comment]
EOFError isnt yet reproducible on mac and could be a windows issue

**Comment by MauroCarolli** [comment]
V2 issue: HIG and IMP data in Scenario\Run. The runs are loaded but there are no runs to choose from in the drop-down menu. No EOFError, Windows OS, code launched from Anaconda using Spyder.

C:\\xxx\Turbine_400m3s_16m
loading scenario Turbine_400m3s_16m
['Series_08', 'Series_11']
run 1 of 2 runs
loading run Series_08
sensor version: 2
run 2 of 2 runs
loading run Series_11
sensor version: 2
Loading scenario
<_io.TextIOWrapper name='C:\\xxx\scenario_outputs/Turbine_400m3s_16m.json' mode='r' encoding='cp1252'>

**Comment by mcrooks83** [comment]
Hi

firstly do you have latest version? 

if you send me the files i can test also. 

you can also email me at mike.crooks@rightstep-consulting.com and we can troubleshoot on a call?
